### ISSUE TITLE
IndexedDB evaluation scrips fails

### ISSUE THREAD

**Issue by hackermondev** [clouedoc/puppeteer-extra-plugin-session#4]
@clouedoc I am using your package for a private project of mine. Whenever I tried to restore a session, I encounter this error:
```js
Error: Evaluation failed: t
    at ExecutionContext._ExecutionContext_evaluate (/workspace/_______/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:181:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/workspace/_______/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async setIndexedDB (/workspace/_______/node_modules/puppeteer-extra-plugin-session/lib/providers/indexedDb.js:53:5)
    at async IndexedDBStorageProvider.set (/workspace/_______/node_modules/puppeteer-extra-plugin-session/lib/providers/indexedDb.js:29:13)
    at async /workspace/_______/node_modules/puppeteer-extra-plugin-session/lib/session.js:31:13
    at async Promise.all (index 3)
    at async setSessionData (/workspace/_______/node_modules/puppeteer-extra-plugin-session/lib/session.js:28:5)
    at async SessionManager.restore (/workspace/_______/node_modules/puppeteer-extra-plugin-session/lib/classes/session-manager.js:30:9)
```

After some digging, I found that it was related to this line of code: https://github.com/clouedoc/puppeteer-extra-plugin-session/blob/master/src/providers/indexedDb.ts#L70

The script it's using to restore the indexedDB is error-ing. I changed some code in the source code of the package in my node_modules folder so it would write the code it was trying to evaluate to a a file on my machine so I could try and evaluate it on my Chrome browser and see the issue.

When I evaluated the code on my own Chrome browser, I got this error:
```json
{
    "_e": {},
    "name": "DataError",
    "message": "Failed to execute 'put' on 'IDBObjectStore': The object store uses out-of-line keys and has no key generator and the key parameter was not provided.\n DataError: Failed to execute 'put' on 'IDBObjectStore': The object store uses out-of-line keys and has no key generator and the key parameter was not provided.",
    "inner": {
        "stack": "Error: Failed to execute 'put' on 'IDBObjectStore': The object store uses out-of-line keys and has no key generator and the key parameter was not provided.\n    at <anonymous>:9:44462\n    at t (<anonymous>:9:9543)\n    at new Fe (<anonymous>:9:9836)\n    at Object.mutate (<anonymous>:9:43597)\n    at Object.mutate (<anonymous>:9:59499)\n    at <anonymous>:9:24296\n    at o (<anonymous>:9:18208)\n    at <anonymous>:9:41336\n    at t (<anonymous>:9:9543)\n    at new Fe (<anonymous>:9:9836)\n    at un._promise (<anonymous>:9:41309)\n    at It._trans (<anonymous>:9:18279)\n    at It.bulkPut (<anonymous>:9:23958)\n    at <anonymous>:12:49239\n    at <anonymous>:12:1439\n    at Object.next (<anonymous>:12:1544)\n    at <anonymous>:12:925\n    at Object.next (<anonymous>:12:1544)\n    at s (<anonymous>:12:315)\n    at <anonymous>:9:16737\n    at We (<anonymous>:9:11148)\n    at Ge (<anonymous>:9:11624)\n    at <anonymous>:9:11988\n    at IDBRequest.v (<anonymous>:9:44632)"
    }
}
```

I don't have any experiencing with using IndexedDB so I have no idea what the error means. Do you know the issue and how I can fix it? @clouedoc

**Comment by hackermondev** [comment]
Turns out it was an issue with how I was saving the session data before restoring it.

**Comment by clouedoc** [comment]
Hello @hackermondev, glad that the plugin works for you and that you resolved your issue 👍
